spring.config.import=optional:classpath:local.properties
spring.application.name=ChessServer
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/chess_db
spring.datasource.username=Thanglm2006
spring.datasource.password=Thanglm2006
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/api
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=10

jwt.secret=yciv2q938fo239fbq2f3ep0hfe9q2309dhq32j0doinqwendqo
jwt.expiration=86400000